# Generated by Django 5.0.7 on 2024-08-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
