# Generated by Django 5.0.7 on 2024-07-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Title')),
                ('Image', models.ImageField(blank=True, upload_to='images/')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('Description', models.TextField(max_length=100, verbose_name='Description')),
            ],
        ),
    ]
