# Generated by Django 5.0.7 on 2024-07-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Title',
            new_name='Name',
        ),
    ]
