# Generated by Django 5.0.7 on 2024-08-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Description',
            field=models.TextField(max_length=1200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
    ]
