# Generated by Django 5.0.7 on 2024-08-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_vacancyform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
    ]
